steps:
- name: node:16-alpine
  entrypoint: npm
  args: ['install']

# run tests
# TODO: The tests seems to require database access, look into adding a fake db to the pipeline.
# - name: node:16-alpine
#   entrypoint: npm
#   args: ['run', 'test']

# build and push the docker image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/realworld:$SHORT_SHA', '.' ]

images:
- 'gcr.io/$PROJECT_ID/realworld:$SHORT_SHA'
